# -*- coding: utf-8 -*-
"""Copy of UAS ADBC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nPyAyXiusS_F4GRgM9kY9MT9wn_pQq29

# DATA UNDERSTANDING DAN DATA PREPARATION
"""

# Install dan autentikasi BigQuery di Google Colab
!pip -q install google-cloud-bigquery

from google.colab import auth
auth.authenticate_user()

from google.cloud import bigquery
import pandas as pd
import numpy as np

PROJECT_ID = "st-project-488506"  # Ganti sesuai PROJECT ID di Google Cloud Anda
DATASET_NAME = "uas_adbc"

TABLE_NAME = "dataset_uas"  # Ganti dengan tabel BigQuery yang diberikan dosen
print("Table yang digunakan:", TABLE_NAME)

client = bigquery.Client(project=PROJECT_ID)
print("BigQuery client siap digunakan.")

def run_query(query: str) -> pd.DataFrame:
    return client.query(query).to_dataframe()

FULL_TABLE = f"`{PROJECT_ID}.{DATASET_NAME}.{TABLE_NAME}`"
print("Table aktif:", FULL_TABLE)

try:
    dataset = client.get_dataset(DATASET_NAME) # Membuat permintaan suatu API.
    print(f"Dataset {DATASET_NAME} already exists.")
except Exception as e:
    dataset = bigquery.Dataset(f"{PROJECT_ID}.{DATASET_NAME}")  # Spesifikasi dataset ID
    dataset.location = "US"  # Mengatur lokasi geographic untuk dataset. Anda mungkin perlu mengubahnya jika menggunakan region lainnya.

from google.colab import files

uploaded = files.upload()

csv_file_name = next(iter(uploaded))

table_id = f"{PROJECT_ID}.{DATASET_NAME}.{TABLE_NAME}"

job_config = bigquery.LoadJobConfig(
    source_format=bigquery.SourceFormat.CSV,
    skip_leading_rows=1,
    autodetect=True,
    field_delimiter=','
)

with open(csv_file_name, "rb") as source_file:
    job = client.load_table_from_file(source_file, table_id, job_config=job_config)

job.result()

print(f"Loaded {job.output_rows} rows into {table_id}")

"""# PROSES PEMBERSIHAN DATA"""

query_preview = f"""
SELECT *
FROM {FULL_TABLE}
LIMIT 10
"""
df_preview = client.query(query_preview).to_dataframe()
df_preview

sql_struktur = f"""
SELECT
  COUNT(*)                              AS jumlah_observasi,
  COUNT(DISTINCT event_id)              AS unique_event_id,
  COUNT(DISTINCT district_city)         AS jumlah_wilayah,
  MIN(event_date)                       AS tanggal_awal,
  MAX(event_date)                       AS tanggal_akhir,
  DATE_DIFF(MAX(event_date),
            MIN(event_date), DAY)        AS rentang_hari
FROM {FULL_TABLE}
"""
df_struktur = run_query(sql_struktur)
display(df_struktur)

# Tipe data kolom via INFORMATION_SCHEMA
sql_schema = f"""
SELECT
  column_name   AS variabel,
  data_type     AS tipe_data,
  is_nullable   AS nullable
FROM `{PROJECT_ID}.{DATASET_NAME}`.INFORMATION_SCHEMA.COLUMNS
WHERE table_name = '{TABLE_NAME}'
ORDER BY ordinal_position
"""
df_schema = run_query(sql_schema)
display(df_schema)

# CEK MISSING VALUES
query = """
SELECT
COUNTIF(event_id IS NULL) AS missing_id,
COUNTIF(event_date IS NULL) AS missing_date,
COUNTIF(district_city IS NULL) AS missing_city,
COUNTIF(rainfall_mm IS NULL) AS missing_mm
FROM `st-project-488506.uas_adbc.dataset_uas`;
"""

df_missing_counts = run_query(query)
df_missing_counts

# CEK DUPLIKASI DATA
query_duplicates = f'''
SELECT
  COUNT(*) AS total_rows,
  COUNT(DISTINCT event_id) AS unique_event_id,
  COUNT(*) - COUNT(DISTINCT event_id) AS duplicate_event_id
FROM {FULL_TABLE}
'''
result_duplicates = client.query(query_duplicates).to_dataframe()
result_duplicates

sql_kualitas = f"""
SELECT
  COUNTIF(rainfall_mm < 0)               AS rainfall_negatif,
  COUNTIF(rainfall_mm = 0)               AS rainfall_nol
FROM {FULL_TABLE}
"""
df_kualitas = run_query(sql_kualitas)
display(df_kualitas.T.rename(columns={0:'Nilai'}))

# pembersihan dan transformasi data
sql_bersih = f"""
WITH deduplicated AS (
  SELECT
    *,
    ROW_NUMBER() OVER (
      PARTITION BY event_id
      ORDER BY event_date
    ) AS rn
  FROM {FULL_TABLE}
  WHERE
    event_id      IS NOT NULL
    AND event_date    IS NOT NULL
    AND district_city IS NOT NULL
    AND rainfall_mm   IS NOT NULL
    AND rainfall_mm   >= 0
)
SELECT
  event_id,
  event_date,
  INITCAP(TRIM(district_city))          AS district_city,
  rainfall_mm,
  -- Kolom turunan
  EXTRACT(YEAR  FROM event_date)        AS tahun,
  EXTRACT(MONTH FROM event_date)        AS bulan,
  FORMAT_DATE('%Y-%m', event_date)      AS year_month,
  DATE_TRUNC(event_date, MONTH)         AS bulan_dt
FROM deduplicated
WHERE rn = 1
ORDER BY event_date
"""

df = run_query(sql_bersih)
df['event_date'] = pd.to_datetime(df['event_date'])
df['bulan_dt']   = pd.to_datetime(df['bulan_dt'])

print(f'✅ Dataset bersih: {len(df):,} baris, {df.shape[1]} kolom')
display(df.head())

"""# EXPLORATORY DATA ANALYSIS (EDA)"""

sql_stats = f"""
SELECT
  COUNT(*)                                      AS n,
  ROUND(AVG(rainfall_mm), 2)                    AS mean,
  ROUND(STDDEV(rainfall_mm), 2)                 AS std_dev,
  ROUND(MIN(rainfall_mm), 2)                    AS min,
  ROUND(APPROX_QUANTILES(rainfall_mm, 100)[OFFSET(25)], 2) AS Q1,
  ROUND(APPROX_QUANTILES(rainfall_mm, 100)[OFFSET(50)], 2) AS median,
  ROUND(APPROX_QUANTILES(rainfall_mm, 100)[OFFSET(75)], 2) AS Q3,
  ROUND(MAX(rainfall_mm), 2)                    AS max,
  ROUND(APPROX_QUANTILES(rainfall_mm, 100)[OFFSET(90)], 2) AS P90,
  ROUND(APPROX_QUANTILES(rainfall_mm, 100)[OFFSET(95)], 2) AS P95,
  ROUND(APPROX_QUANTILES(rainfall_mm, 100)[OFFSET(99)], 2) AS P99
FROM (
  SELECT rainfall_mm FROM {FULL_TABLE}
  WHERE rainfall_mm IS NOT NULL AND rainfall_mm >= 0
)
"""
df_stats = run_query(sql_stats)
display(df_stats.T.rename(columns={0:'Nilai'}))

#stat deskriptif per tahun
sql_stats_tahun = f"""
SELECT
  EXTRACT(YEAR FROM event_date)               AS tahun,
  COUNT(*)                                    AS n,
  ROUND(AVG(rainfall_mm), 2)                  AS mean,
  ROUND(STDDEV(rainfall_mm), 2)               AS std_dev,
  ROUND(MIN(rainfall_mm), 2)                  AS min,
  ROUND(MAX(rainfall_mm), 2)                  AS max,
  ROUND(APPROX_QUANTILES(rainfall_mm,100)[OFFSET(50)], 2) AS median
FROM {FULL_TABLE}
WHERE rainfall_mm IS NOT NULL AND rainfall_mm >= 0
GROUP BY tahun
ORDER BY tahun
"""
df_stats_tahun = run_query(sql_stats_tahun)
display(df_stats_tahun)

# distribusi data numerik
import matplotlib.pyplot as plt

numeric_cols = ['rainfall_mm']
df[numeric_cols].hist(figsize=(8,5))

plt.suptitle('Distribusi Data Numerik')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# identifikasi pola musiman
sql_musiman = f"""
SELECT
  EXTRACT(MONTH FROM event_date)        AS bulan,
  FORMAT_DATE('%b', DATE(2024, CAST(EXTRACT(MONTH FROM event_date) AS INT64), 1))
                                        AS nama_bulan,
  ROUND(AVG(rainfall_mm), 2)            AS rata_rata,
  ROUND(MAX(rainfall_mm), 2)            AS maks
FROM {FULL_TABLE}
WHERE rainfall_mm IS NOT NULL AND rainfall_mm >= 0
GROUP BY bulan, nama_bulan
ORDER BY bulan
"""
df_musiman = run_query(sql_musiman)

sql_heatmap = f"""
SELECT
  EXTRACT(MONTH FROM event_date) AS bulan,
  EXTRACT(YEAR  FROM event_date) AS tahun,
  ROUND(AVG(rainfall_mm), 2)     AS rata_rata
FROM {FULL_TABLE}
WHERE rainfall_mm IS NOT NULL AND rainfall_mm >= 0
GROUP BY bulan, tahun
ORDER BY bulan, tahun
"""
df_heatmap = run_query(sql_heatmap)

fig, ax = plt.subplots(1, 2, figsize=(14, 5))

# bar plot musiman
ax[0].bar(df_musiman['nama_bulan'], df_musiman['rata_rata'])
ax[0].set_title('Rata-rata Curah Hujan per Bulan')
ax[0].set_ylabel('Curah Hujan (mm)')

# heatmap
pivot = df_heatmap.pivot(index='bulan', columns='tahun', values='rata_rata')
sns.heatmap(
    pivot,
    annot=True,
    fmt='.0f',
    cmap='YlOrRd',
    ax=ax[1]
)
ax[1].set_title('Heatmap Curah Hujan')

plt.tight_layout()
plt.show()

# rata-rata hujan per wilayah
sql_wilayah = f"""
SELECT
  INITCAP(TRIM(district_city))           AS wilayah,
  COUNT(*)                               AS n,
  ROUND(AVG(rainfall_mm), 2)             AS rata_rata,
  ROUND(STDDEV(rainfall_mm), 2)          AS std_dev,
  ROUND(MIN(rainfall_mm), 2)             AS min,
  ROUND(MAX(rainfall_mm), 2)             AS maks,
  ROUND(APPROX_QUANTILES(rainfall_mm,100)[OFFSET(50)], 2) AS median
FROM {FULL_TABLE}
WHERE rainfall_mm IS NOT NULL AND rainfall_mm >= 0
  AND district_city IS NOT NULL
GROUP BY wilayah
ORDER BY rata_rata DESC
LIMIT 10
"""
df_wilayah = run_query(sql_wilayah)
display(df_wilayah)

plt.figure(figsize=(8,5))

plt.barh(df_wilayah['wilayah'], df_wilayah['rata_rata'])
plt.gca().invert_yaxis()

plt.title('Top 10 Wilayah dengan Curah Hujan Tertinggi')
plt.xlabel('Rata-rata Curah Hujan (mm)')

plt.tight_layout()
plt.show()

# visualisasi top 10 wilayah berdasarkan jumlah kejadian
query_top_wilayah = f"""
SELECT
  district_city,
  COUNT(*) AS total_kejadian
FROM {FULL_TABLE}
GROUP BY district_city
ORDER BY total_kejadian DESC
LIMIT 10
"""

top_wilayah = run_query(query_top_wilayah)
display(top_wilayah)

plt.figure(figsize=(10,6))

sns.barplot(
    data=top_wilayah,
    x='total_kejadian',
    y='district_city'
)

plt.title('Top 10 Wilayah dengan Jumlah Kejadian Terbanyak')

plt.xlabel('Jumlah Kejadian')

plt.ylabel('Wilayah')

plt.show()

"""# ANALISIS TREN

"""

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import numpy as np

# TREN BULANAN: rata-rata curah hujan per bulan
sql_tren_bulanan = f"""
SELECT
  DATE_TRUNC(event_date, MONTH)          AS bulan_dt,
  FORMAT_DATE('%Y-%m', event_date)       AS year_month,
  COUNT(*)                               AS n_observasi,
  ROUND(AVG(rainfall_mm), 2)             AS rata_curah_hujan,
  ROUND(MAX(rainfall_mm), 2)             AS maks_curah_hujan,
  ROUND(STDDEV(rainfall_mm), 2)          AS std_dev
FROM {FULL_TABLE}
WHERE rainfall_mm IS NOT NULL AND rainfall_mm >= 0
GROUP BY bulan_dt, year_month
ORDER BY bulan_dt
"""
df_tren = run_query(sql_tren_bulanan)
df_tren['bulan_dt'] = pd.to_datetime(df_tren['bulan_dt'])

# konversi tanggal
df_tren['bulan_dt'] = pd.to_datetime(df_tren['bulan_dt'])

# garis tren
x = np.arange(len(df_tren))
z = np.polyfit(x, df_tren['rata_curah_hujan'], 1)

# visualisasi
plt.figure(figsize=(14,5))

plt.plot(
    df_tren['bulan_dt'],
    df_tren['rata_curah_hujan'],
    marker='o',
    label='Rata-rata Bulanan'
)

plt.plot(
    df_tren['bulan_dt'],
    np.poly1d(z)(x),
    linestyle='--',
    label='Tren Linear'
)

plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%b\n%Y'))

plt.title('Tren Curah Hujan Bulanan Jawa Barat 2020–2025')
plt.xlabel('Waktu')
plt.ylabel('Curah Hujan (mm)')
plt.legend()

plt.tight_layout()
plt.show()

print(f"Slope tren : {z[0]:.4f} mm/bulan")
print(f"Arah tren         : {'📈 NAIK' if z[0]>0 else '📉 TURUN'}")

!pip install pymannkendall

# Mann-Kendall menggunakan data hasil query BigQuery
import pymannkendall as mk

series = df_tren['rata_curah_hujan'].values
result = mk.original_test(series)

print(f'  Tren          : {result.trend}')
print(f'  H0 ditolak?   : {result.h}')
print(f'  p-value       : {result.p:.4f}')
print(f'  Statistik (s) : {result.s}')
print(f'  Var(s)        : {result.var_s:.2f}')
print(f'  Tau           : {result.Tau:.4f}')
print(f'  z             : {result.z:.4f}')
print()
alpha = 0.05
if result.p < alpha:
    print(f'✅ Terdapat tren {result.trend} yang SIGNIFIKAN (p={result.p:.4f} < α={alpha}).')
else:
    print(f'❌ Tidak terdapat tren yang signifikan (p={result.p:.4f} ≥ α={alpha}).')

# tren curah hujan per wilayah top (10)
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

sql_tren_wil = f"""
WITH top_wilayah AS (
  SELECT INITCAP(TRIM(district_city)) AS wilayah
  FROM {FULL_TABLE}
  WHERE district_city IS NOT NULL
  GROUP BY wilayah
  ORDER BY COUNT(*) DESC
  LIMIT 10
)
SELECT
  DATE_TRUNC(event_date, MONTH)          AS bulan_dt,
  INITCAP(TRIM(t.district_city))         AS wilayah,
  ROUND(AVG(t.rainfall_mm), 2)           AS rata_curah_hujan
FROM {FULL_TABLE} t
JOIN top_wilayah tw
  ON INITCAP(TRIM(t.district_city)) = tw.wilayah
WHERE t.rainfall_mm IS NOT NULL AND t.rainfall_mm >= 0
GROUP BY bulan_dt, wilayah
ORDER BY bulan_dt, wilayah
"""
df_tren_wil = run_query(sql_tren_wil)
df_tren_wil['bulan_dt'] = pd.to_datetime(df_tren_wil['bulan_dt'])

# KONVERSI TANGGAL
df_tren_wil['bulan_dt'] = pd.to_datetime(df_tren_wil['bulan_dt'])

# VISUALISASI
plt.figure(figsize=(14,5))

for wilayah, data in df_tren_wil.groupby('wilayah'):
    plt.plot(data['bulan_dt'], data['rata_curah_hujan'], label=wilayah)

plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%b\n%Y'))

plt.title('Tren Curah Hujan per Wilayah')
plt.xlabel('Waktu')
plt.ylabel('Curah Hujan (mm)')
plt.legend(bbox_to_anchor=(1.02, 1), loc='upper left')

plt.tight_layout()
plt.show()